const BUDGET_ESTIMATE = {
  SHEET_NAME: 'BE-001',
  CELL_PROGRAM: 'F4',
  CELL_OUTPUT: 'F5',
  CELL_OUTPUT_INDICATOR: 'F6',
  CELL_ACTIVITY: 'F7',
  CELL_ACTIVITY_INDICATOR: 'F8',
  CELL_START_DATE: 'G13',
  CELL_VENUE: 'O13',
  CELL_TOTAL_PAX: 'H16',
  ROW_BOARD_LODGING_START: 17,
  ROW_BOARD_LODGING_END: 20,
  ROW_BOARD_LODGING_OTHER: 24,
  ROW_TRAVEL_REGION_START: 29,
  ROW_TRAVEL_REGION_END: 47,
  ROW_TRAVEL_CO_START: 48,
  ROW_TRAVEL_CO_END: 50,
  ROW_TRAVEL_OTHER: 54,
  ROW_HONORARIUM_START: 58,
  ROW_HONORARIUM_END: 59,
  ROW_SUPPLIES_CONTINGENCY_START: 60,
  ROW_SUPPLIES_CONTINGENCY_END: 61,
  COL_BOARD_LODGING: 'C',
  COL_TRAVEL_REGION: 'D',
  COL_TRAVEL_CO: 'C',
  COL_TRAVEL_OTHER: 'C',
  COL_HONORARIUM: 'C',
  COL_SUPPLIES_CONTINGENCY: 'B',
  COL_NUM_PAX: 'H',
  COL_DAYS: 'J',
  COL_AMOUNT: 'K',
  NON_PAX_KEYWORDS: ['Resource', 'Technical', 'Bureau', 'Other'],
} as const;

const EXPENDITURE_MATRIX = {
  SHEET_NAME: 'Expenditure Form',
  CELL_PROGRAM: 'C13',
  CELL_OUTPUT: 'D14',
  CELL_OUTPUT_INDICATOR: 'H14',
  CELL_ACTIVITY: 'G17',
  CELL_ACTIVITY_INDICATOR: 'H17',
  ROW_EXPENSE_ITEM_START_ROW: 18,
  ROW_EXISTING_EXPENSE_ITEM_ROWS: 4,
  COL_EXPENSE_GROUP: 'J',
  COL_GAA_OBJECT: 'L',
  COL_EXPENSE_ITEM: 'N',
  COL_QUANTITY: 'O',
  COL_FREQUENCY: 'Q',
  COL_UNIT_COST: 'P',
  COL_TOTAL_COST: 'R',
  COL_LOCATION_TEV: 'S',
  COL_PPMP: 'T',
  COL_APP_SUPPLIES: 'U',
  COL_APP_TICKET: 'V',
  COL_MANNER_OF_RELEASE: 'W',
  COL_TOTAL_OBLIGATION: 'AR',
  COL_TOTAL_DISBURSEMENT: 'BE',
  COL_COSTING_QUANTITY: 'O',
  COL_COSTING_UNIT_COST: 'P',
  COL_COSTING_FREQUENCY: 'Q',
  COL_OBLIGATION_MONTH_START: 'AS',
  COL_OBLIGATION_MONTH_END: 'BD',
  COL_DISBURSEMENT_MONTH_START: 'BF',
  COL_DISBURSEMENT_MONTH_END: 'BQ',
  COL_OBLIGATION_MONTH_START_INDEX: 45,
  COL_DISBURSEMENT_MONTH_START_INDEX: 58,
  COL_PHYSICAL_TARGET_MONTH_START_INDEX: 32,
} as const;

const EXPENSE_PREFIX = {
  BOARD_LODGING: 'Board and Lodging of ',
  TRAVEL: 'Travel Expenses of ',
  HONORARIUM: 'Honorarium of ',
} as const;

const EXPENSE_GROUP = {
  TRAINING_SCHOLARSHIPS_EXPENSES: 'Training and Scholarship Expenses',
  SUPPLIES_EXPENSES: 'Supplies and Materials Expenses',
} as const;

const GAA_OBJECT = {
  TRAINING_EXPENSES: 'Training Expenses',
  OTHER_SUPPLIES: 'Other Supplies and Materials Expenses',
} as const;

const MANNER_OF_RELEASE = {
  FOR_DOWNLOAD_BOARD: 'For Downloading (Board and Lodging)',
  FOR_DOWNLOAD_PSF: 'For Downloading (Program Support Funds)',
  DIRECT_PAYMENT: 'Direct Payment',
  CASH_ADVANCE: 'Cash Advance',
} as const;

const CONVERT_URL = '/api/convert';

const EXCEL_MIMETYPE =
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

export {
  BUDGET_ESTIMATE,
  EXPENDITURE_MATRIX,
  EXPENSE_PREFIX,
  GAA_OBJECT,
  MANNER_OF_RELEASE,
  EXPENSE_GROUP,
  CONVERT_URL,
  EXCEL_MIMETYPE,
};
